steps:
- name: 'gcr.io/cloud-builders/java/mvn'
  env:
  - "GCE_PROJECT_ID=test-project"
  args: ['package']
  dir: 'delivery-management-system'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/driver-management-system:$BRANCH_NAME', '.']
  dir: 'delivery-management-system/target'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/delivery-management-system:$BRANCH_NAME']
- name: 'grc.io/$PROJECT_ID/helm-build'
  args: ['upgrade','--install','scaffolding','scaffolding']
  dir: 'devops/kubernetes/helm-deployments'
- name: 'grc.io/$PROJECT_ID/helm-build'
  args: ['upgrade','--install','keycloak','keycloak']
  dir: 'devops/kubernetes/helm-deployments'
- name: 'grc.io/$PROJECT_ID/helm-build'
  args: ['upgrade','--install','delivery-management-system','delivery-management-system']
  dir: 'devops/kubernetes/helm-deployments'