version: '2.1'
services:
  pubsub-emulator:
    build:
      context: pubsub-emulator
      dockerfile: Dockerfile
    ports:
    - 8086:8086
    volumes:
      - ./data/pubsub:/var/lib/pubsub
  keycloak:
    build:
      context: keycloak
      dockerfile: Dockerfile
    ports:
    - 8081:8080
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USERNAME=keycloak-dev
      - MYSQL_PASSWORD=password
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - KEYCLOAK_PASSWORD=password
      - KEYCLOAK_USER=admin
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
  mysql:
    image: healthcheck/mysql
    ports:
    - 3306:3306
    volumes:
      - ./data/mysql-db:/var/lib/mysql
      - ./init-db.sql:/init-db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: ['mysqld','--init-file=/init-db.sql']
  osrm:
    build:
      context: osrm
      dockerfile: Dockerfile
    ports:
    - 5000:5000

  wait_for_startup:
    image: busybox
    depends_on:
      mysql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      osrm:
        condition: service_healthy
      pubsub-emulator:
        condition: service_healthy
