apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: "{{ .Chart.Name }}"
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    name: {{ template "fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak-mysql:{{ .Values.image.tag }}
        imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
        env:
        - name: KEYCLOAK_LOGLEVEL
          value: {{.Values.logLevel}}
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              name: {{.Values.credentials.keycloak.user}}
              key: username
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{.Values.credentials.keycloak.user}}
              key: password
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: localhost
        - name: MYSQL_PORT_3306_TCP_PORT
          value: 3306
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{.Values.credentials.cloudsql.db}}
              key: database
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{.Values.credentials.cloudsql.db}}
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{.Values.credentials.cloudsql.db}}
              key: password
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
      - image: gcr.io/cloudsql-docker/gce-proxy:1.10
        name: cloudsql-proxy
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=pizzatent-175310:australia-southeast1:test-pizza-cloud-sql=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: {{.Values.credentials.cloudsql.instance}}
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
      - name: cloudsql
        emptyDir: