hostName: key.example.com

imageTag: 0.0.3
keyCloakVersion: latest
keycloakUser: admin
keycloakPass: admin123

containerPort: 8080

logLevel: INFO

postgres:
  databasePort: 3306
  databaseName: keycloak
  databaseUser: keycloak
  databasePassword: keycloak
  persistence:
    path: /data/keycloak/mysql
