apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: "{{ .Chart.Name }}"
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    provider: "pizzatent"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        provider: "pizzatent"
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: "jboss/keycloak-postgres:{{ .Values.keyCloakVersion }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        - name: KEYCLOAK_LOGLEVEL
          value: {{ .Values.logLevel }}
        - name: KEYCLOAK_USER
          value: {{ .Values.keycloakUser }}
        - name: KEYCLOAK_PASSWORD
          value: {{ .Values.keycloakPass }}
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: {{ .Release.Name }}-mysql
# this is more then a default value, it is the set value of all mysql
# database servers
        - name: POSTGRES_PORT_5432_TCP_ADDR
          value: {{ .Values.postgres.databaseUrl | quote }}
        - name: POSTGRES_PORT_5432_TCP_PORT
          value: {{ .Values.postgres.databasePort | quote }}
        - name: POSTGRES_DATABASE
          value: {{ .Values.postgres.databaseName }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.databaseUser }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-mysql"
              key: database-password
        ports:
        - name: http
          containerPort: {{ .Values.containerPort }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
