## kube-lego configuration
## Ref: https://github.com/jetstack/kube-lego
##
kube-lego:
  config:
    ## Email address to use for registration with Let's Encrypt
    ##
    # LEGO_EMAIL: my@email.tld
    LEGO_EMAIL: samgurtman@gmail.com
    ## Let's Encrypt API endpoint
    ## Production: https://acme-v01.api.letsencrypt.org/directory
    ## Staging: https://acme-staging.api.letsencrypt.org/directory
    ##
    LEGO_URL: https://acme-v01.api.letsencrypt.org/directory

    ## kube-lego port
    ##
    LEGO_PORT: 8080

  ## kube-lego image
  ##
  image:
    repository: jetstack/kube-lego
    tag: 0.1.4
    pullPolicy: IfNotPresent

  ## Node labels for pod assignment
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}

  ## Annotations to be added to pods
  ##
  podAnnotations: {}

  replicaCount: 1

  ## kube-lego resource limits & requests
  ## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}
    # limits:
    #   cpu: 20m
    #   memory: 8Mi
    # requests:
    #   cpu: 20m
    #   memory: 8Mi


external-dns:

  ## Details about the image to be pulled.
  image:
    name: registry.opensource.zalan.do/teapot/external-dns
    tag: v0.4.2
    pullPolicy: IfNotPresent

  ## This controls which types of resource external-dns should 'watch' for new
  ## DNS entries.
  source:
    - service

  ## The DNS provider where the DNS records will be created (options: aws, google, inmemory, azure )
  provider: google

  ## Limit possible target zones by a domain suffix (optional)
  # domainFilter:

  ## Modify how DNS records are sychronized between sources and providers (options: sync, upsert-only )
  policy: sync

  ## Annotations to be added to pods
  ##
  # podAnnotations: {}

  extraArgs:
    txt-owner-id: pizzatent
    google-project: pizzatent-175310


  ## CPU and Memory limit and request for external-dns
  resources: {}
  #  limits:
  #    memory: 50Mi
  #  requests:
  #    memory: 50Mi
  #    cpu: 10m

  # Should the chart create and use a service account.
  # serviceAccountEnabled: false

  # If creating a service account, you can optionally override the name used.
  # Defaults to .Release.Name-external-dns-sa. Note: Release.Name is always
  # included to prevent collisions.
  # saNameOverride:
